name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install .NET Aspire workload
      run: |
        dotnet nuget locals all --clear
        dotnet workload install aspire --skip-manifest-update
        dotnet workload update
        dotnet workload list
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:csharp"
    
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    
    - name: Run dotnet format check
      run: dotnet format --verify-no-changes --verbosity diagnostic

    - name: Clean solution
      run: dotnet clean